source "https://rubygems.org"

gem "net-smtp", "~> 0.3"
gem "pony",     "~> 1.13"
gem "puma",     "~> 5.6"
gem "sinatra",  "~> 4.0"

gem "opentelemetry-sdk",                     "~> 1.5"
gem "opentelemetry-exporter-otlp",           "~> 0.29"
gem "opentelemetry-instrumentation-sinatra", "~> 0.24"
